export const LOCK_TYPE_DIC = [
  { label: '系统锁定', value: 'SYSTEM' },
  { label: '手动锁定', value: 'MANUAL' },
];

export const LOCK_STATUS_DIC = [
  { label: '待锁定', value: 'PRE_LOCKED' },
  { label: '锁定中', value: 'LOCKED' },
  { label: '已解锁', value: 'UN_LOCKED' },
];

export const authLockOption = {
  tip: false,
  searchShow: true,
  searchMenuSpan: 6,
  border: true,
  index: true,
  addBtn: false,
  viewBtn: false,
  editBtn: false,
  delBtn: false,
  menuWidth: 160,
  dialogType: 'drawer',
  dialogWidth: 800,
  dialogClickModal: false,
  column: [
    {
      label: '锁定目标',
      prop: 'lockTarget',
      slot: true,
      search: true,
      span: 24,
      searchPlaceholder: '请输入账号或IP',
    },
    {
      label: '用户姓名',
      prop: 'userName',
      slot: true,
      width: 100,
    },
    {
      label: '请求IP',
      prop: 'remoteIp',
      slot: true,
      search: true,
      searchPlaceholder: '请输入IP地址',
      width: 160,
    },
    {
      label: '失败次数',
      prop: 'failCount',
      width: 80,
      align: 'center',
      hide: true,
    },
    {
      label: '用户代理',
      prop: 'userAgent',
      hide: true,
      overHidden: true,
    },
    {
      label: '锁定类型',
      prop: 'lockType',
      slot: true,
      type: 'select',
      dicData: LOCK_TYPE_DIC,
      width: 90,
      align: 'center',
    },
    {
      label: '锁定状态',
      prop: 'lockStatus',
      slot: true,
      type: 'select',
      search: true,
      dicData: LOCK_STATUS_DIC,
      width: 90,
      align: 'center',
    },
    {
      label: '锁定开始',
      prop: 'lockBeginTime',
      slot: true,
      width: 120,
    },
    {
      label: '锁定结束',
      prop: 'lockEndTime',
      slot: true,
      width: 120,
    },
    {
      label: '锁定原因',
      prop: 'lockReason',
      type: 'textarea',
      hide: true,
      overHidden: true,
      minWidth: 160,
      span: 24,
    },
    {
      label: '解锁原因',
      prop: 'unlockReason',
      type: 'textarea',
      hide: true,
      overHidden: true,
      span: 24,
    },
  ],
};
